V2.8.2 release/jitpack support
useriq-com/android-sdk pull request #2
Opened 2021-04-30 06:22 UTC by BhavaniPrasadUserIQ

UserIQ SDK Version 2.8.2 release - Added Jitpack Support

2021-04-30 13:44 UTC, sudhakar requested changes
Make changes

2021-04-30 13:44 UTC, sudhakar commented on Sample app/app/build.gradle
> +    // implementation 'com.useriq:sdk:2.6.0'
```suggestion
```
Why is old comment left behind?

2021-04-30 13:44 UTC, sudhakar commented on jitpack.yml
> +  - mvn install:install-file $FILE -DgroupId=ccom.github.useriq-com -DartifactId=android-sdk -Dversion=2.8.2 -Dpackaging=aar -DgeneratePom=true
```suggestion
  - mvn install:install-file $FILE -DgroupId=com.github.useriq-com -DartifactId=android-sdk -Dversion=2.8.2 -Dpackaging=aar -DgeneratePom=true
```

2021-05-03 07:13 UTC, BhavaniPrasadUserIQ commented on Sample app/app/build.gradle
> +    // implementation 'com.useriq:sdk:2.6.0'
Removed old comment.

2021-05-03 07:13 UTC, BhavaniPrasadUserIQ commented on jitpack.yml
> +  - mvn install:install-file $FILE -DgroupId=ccom.github.useriq-com -DartifactId=android-sdk -Dversion=2.8.2 -Dpackaging=aar -DgeneratePom=true
Updated DgroupID, Thanks!

2021-05-04 05:55 UTC, sudhakar approved these changes

2021-05-04 06:54 UTC, merged